twig:
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        titres: '@App\Twig\OuvragesTitreExtension'
        slogan: '@App\Twig\SloganExtension'

when@test:
    twig:
        strict_variables: true
